### ISSUE TITLE
makeHash returns same value in separate executions

### ISSUE THREAD

**Issue by Amaranthos** [Abscissa/DAuth#4]
It appears that 

`makeHash("password".dup.toPassword).toString`

returns different values with the same execution of the program,
but returns the same values in the same order in separate executions.

This would mean you are seeding rand with a know value right?

**Comment by Abscissa** [comment]
Shit, that's embarrassing. The RNG (HashDRBGStream) wasn't getting inited.

**Comment by Abscissa** [comment]
Tagged new release: `v0.6.3`
